project:
  type: website

website:
  title: "Savannah M. Hammerton, MS"
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: Projects
        href: projects.qmd
      - text: Publications
        href: publications.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: 
      light: quartz
      dark: vapor
    css: styles.css



